{%- from "heka/map.jinja" import log_collector with context %}
{%- if log_collector.get('enabled', False) %}
server:
  alert:
    HekaOutputQueueStalled:
      if: >-
        heka_output_queue_size > {{ log_collector.heka_queue_size_threshold }}
      labels:
        severity: warning
        service: heka
      annotations:
        summary: 'Heka queue stalled'
{%- raw %}
        description: 'The {{ $labels.queue }} queue is stalled on node {{ $labels.host }} for more than 1 hour. The corresponding Heka service is either down or stuck.'
{%- endraw %}
{%- endif %}
